# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
# Jobs 
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo
    steps:
      - checkout   

      - run:
          name: "installing make"
          command: sudo apt-get update && sudo apt-get -y install make

      - setup_remote_docker

      - run:
          name: "Login into NPAV GCE docker repository" 
          # command: docker login -u ${GCR_DOCKER_RO_USERNAME} -p "$(echo $GCR_DOCKER_RO_PASSWORD)" https://gcr.io
          command: docker login -u _json_key -p "$(echo $GCR_DOCKER_RW_PASSWORD)" https://gcr.io

      - run:
          name: "Building project"
          command: make circleci-docker

      - run:
          name: "Push image to GCR"
          command: |
            # Only push docker image when on master branch on the Accedian project
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_PROJECT_USERNAME}" == "Accedian" ]; then
              echo $GCLOUD_SERVICE_KEY | base64 -d  > ${HOME}/gcloud-service-key.json
              docker login -u _json_key -p "$(echo $GCR_DOCKER_RW_PASSWORD)" https://gcr.io
              echo "Now Tagging"
              git config --global user.email "${CIRCLE_USERNAME}@accedian.com"
              git config --global user.name "CircleCI"
              git semver minor
              export DOCKER_VER=$(git semver get)
              git push origin master ${DOCKER_VER}
              make circleci-push  
            fi

workflows:
  version: 2
  build_and_release: 
    jobs:
      - build:
          context: org-global
